<a href="https://colab.research.google.com/github/Sesatt/Jane-Street-Puzzle-June22/blob/main/JaneStreet_Puzzle_June2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from math import sqrt

In [ ]:
#define the starting puzzle
start_board_large = np.array([
    [0,3,0,0,0,7,0,0,0,0],
    [0,0,0,4,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,2,0],
    [0,0,0,1,0,0,0,0,0,0],
    [6,0,1,0,0,0,1,0,0,0],
    [0,1,0,0,1,0,1,3,0,6],
    [0,0,0,0,0,0,2,0,0,0],
    [0,2,0,0,0,1,0,0,0,0],
    [0,0,0,0,0,0,6,0,0,0],
    [0,0,0,0,5,0,0,0,2,0]
])

#define your final/modified puzzle
board_large = np.array([
    [0,3,0,0,0,7,0,0,0,0],
    [0,0,0,4,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,2,0],
    [0,0,0,1,0,0,0,0,0,0],
    [6,0,1,0,0,0,1,0,0,0],
    [0,1,0,0,1,0,1,3,0,6],
    [0,0,0,0,0,0,2,0,0,0],
    [0,2,0,0,0,1,0,0,0,0],
    [0,0,0,0,0,0,6,0,0,0],
    [0,0,0,0,5,0,0,0,2,0]
])

In [ ]:
#print puzzle
def print_board(board):
    for i in range(len(board)):
        print(board[i])

In [ ]:
print_board(board_large)

[0 3 0 0 0 7 0 0 0 0]
[0 0 0 4 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 2 0]
[0 0 0 1 0 0 0 0 0 0]
[6 0 1 0 0 0 1 0 0 0]
[0 1 0 0 1 0 1 3 0 6]
[0 0 0 0 0 0 2 0 0 0]
[0 2 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 6 0 0 0]
[0 0 0 0 5 0 0 0 2 0]


In [ ]:
# find positions within puzzle that are empty / that need to be filled 
def find_empty(board, boxes):
  for box in boxes:
    for i in range(len(board)):
        for j in range(len(board[0])):
            if (box[i][j] == 1) & (board[i][j] == 0): 
                # print(i,j)
                return (i, j) # row, column
  return None

In [ ]:
find_empty(board_large, boxes)

(6, 2)

In [ ]:
# define the regions within the puzzle
b1 = np.array([
    [1,0,0,0,0,0,0,0,0,0],
    [1,1,0,0,0,0,0,0,0,0],
    [1,1,0,0,0,0,0,0,0,0],
    [1,1,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b2 = np.array([
    [0,1,1,1,0,0,0,0,0,0],
    [0,0,1,1,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b3 = np.array([
    [0,0,0,0,1,1,1,1,1,1],
    [0,0,0,0,0,1,0,0,1,1],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b4 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,1,0,0],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b5 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,1,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b6 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,1,1,0,0,0,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b7 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,1],
    [0,0,0,0,0,0,0,0,1,1],
    [0,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,1,1],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b8 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,1,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b9 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0],
    [0,0,0,1,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b10 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,0,0,0],
    [0,0,0,0,0,1,1,1,0,0],
    [0,0,0,0,0,0,0,1,1,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b11 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,1,0,0,0,0],
    [0,0,0,0,0,1,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b12 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,1,1],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b13 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,0,0,1],
    [0,0,0,0,0,1,1,0,0,1],
    [0,0,0,0,0,0,1,1,1,1]
])
b14 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,1,0],
    [0,0,0,0,0,0,0,1,1,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b15 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,0,1,1,0,0,0,0,0],
    [0,0,0,0,1,1,0,0,0,0]
])
b16 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,1,0,0,0,0,0,0,0,0],
    [1,1,0,0,0,0,0,0,0,0],
    [1,1,1,0,0,0,0,0,0,0],
    [1,1,1,1,0,0,0,0,0,0]
])
b17 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])
b18 = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,0,1,1,1,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0]
])

#sort the regions, starting with that that has highest number of empty fields 
boxes = [b17, b11, b5, b6, b4, b9, b12, b8, b14, b2, b18, b15, b10, b7, b13, b3, b1, b16]

In [ ]:
def valid(board, num, pos):
    #find the box it belongs to
    for i in boxes:
        if i[pos] == 1: 
            if num > sum(i.reshape(-1)):
                # print(str(pos) + " number too large: "+ str(num))
                return False
            box_board = i*board
            if num in box_board.reshape(-1):
                # print(str(pos) + " number already in box: "+ str(num))
                return False
            else: 
                min_dist = 100
                for row in range(len(board)): 
                    for column in range(len(board)): 
                        if board[row][column] == num:
                            min_dist = min(taxicap_distance(pos, (row, column)), min_dist)
                            if min_dist < num: 
                                # print(str(pos) + " incorrect distance: "+ str(num))
                                return False
    # print(str(pos) + " possible solution: " + str(num))
    return True

In [ ]:
def taxicap_distance(pos1, pos2):
    return sum(abs(val1-val2) for val1, val2 in zip (pos1, pos2))

In [ ]:
invalid_pos = []

In [ ]:
def solve(start_board, board, boxes):
    #creat list for positions with incorrect numbers
    invalid_pos = []
      
    #find the next empty field in the box
    find = find_empty(board, boxes)
    print(find)
    
    #if board is full, check whether current solution is correct
    if not find:
        print(start_board)
        
        
        #loop through all numbers to check distances
        for num2 in range(1,11):
            pos_list = []
            #first find positions that have number num2
            for row in range(len(board)): 
                    for column in range(len(board)): 
                        if board[row][column] == num2:
                            pos_list.append((row,column))
            if len(pos_list) != 0:
                for idx in range(len(pos_list)):
                    min_dist = 100
                    for idx2 in range(len(pos_list)):
                        if idx != idx2: 
                            min_dist = min(taxicap_distance(pos_list[idx], pos_list[idx2]), min_dist)
                    if min_dist != num2:
                        invalid_pos.append(pos_list[idx])
        if len(invalid_pos) != 0:
            board = start_board
            print(board)
            find = find_empty(board, boxes)
            row, column = find
            return False
        else: 
            return True
    else: 
        row, column = find
    
    for num in range(1, 11):
        if (row, column) in invalid_pos: 
            num = num + 1
        if valid(board, num, (row, column)):
            board[row][column] = num
            
            if solve(start_board, board, boxes):
                return True
            
            board[row, column] = 0
    
    return False

In [ ]:
solve(start_board_large, board_large, boxes)

Streaming output truncated to the last 5000 lines.
(8, 2)
(8, 0)
(3, 0)
(3, 1)
(5, 0)
(6, 0)
(6, 1)
(7, 0)
(8, 0)
(8, 1)
(8, 2)
(8, 0)
(3, 1)
(2, 1)
(3, 0)
(3, 1)
(5, 0)
(6, 0)
(6, 1)
(7, 0)
(8, 0)
(8, 1)
(8, 2)
(8, 2)
(9, 0)
(3, 1)
(3, 0)
(3, 1)
(3, 1)
(2, 1)
(3, 0)
(3, 1)
(5, 0)
(6, 0)
(6, 1)
(7, 0)
(8, 0)
(8, 1)
(8, 2)
(3, 1)
(1, 0)
(1, 1)
(2, 0)
(2, 1)
(2, 1)
(3, 0)
(3, 1)
(5, 0)
(6, 0)
(6, 1)
(7, 0)
(8, 0)
(8, 1)
(8, 2)
(8, 2)
(9, 0)
(9, 1)
(9, 2)
(8, 1)
(8, 2)
(3, 1)
(2, 1)
(3, 0)
(3, 1)
(5, 0)
(6, 0)
(6, 1)
(7, 0)
(8, 0)
(8, 1)
(8, 2)
(8, 2)
(9, 0)
(9, 1)
(9, 2)
(8, 1)
(8, 2)
(8, 0)
(8, 1)
(8, 2)
(3, 1)
(2, 1)
(3, 0)
(3, 1)
(3, 1)
(1, 1)
(2, 0)
(2, 1)
(3, 0)
(3, 1)
(5, 0)
(6, 0)
(6, 1)
(7, 0)
(8, 0)
(8, 1)
(8, 2)
(8, 2)
(9, 0)
(9, 1)
(9, 2)
(8, 1)
(8, 2)
(3, 1)
(2, 1)
(3, 0)
(3, 1)
(5, 0)
(6, 0)
(6, 1)
(7, 0)
(8, 0)
(8, 1)
(8, 2)
(8, 2)
(9, 0)
(9, 1)
(9, 2)
(8, 1)
(8, 2)
(8, 0)
(8, 1)
(8, 2)
(3, 1)
(2, 1)
(3, 0)
(3, 1)
(3, 1)
(2, 1)
(2, 0)
(2, 1)
(2, 1)
(3, 0)
(3, 1)
(5, 0)
(6, 

True

In [ ]:
board_large

array([[ 4,  3,  6,  5,  3,  7,  4,  9,  6,  5],
       [ 8, 10,  2,  4,  1,  1,  2,  3,  8,  2],
       [ 9,  2,  3,  2,  1,  2,  5,  1,  2,  4],
       [ 5,  7,  2,  1,  2,  6,  3,  1,  1,  3],
       [ 6,  3,  1,  1,  3,  2,  1,  4,  2,  7],
       [ 1,  1,  4,  5,  1,  1,  1,  3,  5,  6],
       [ 3,  1,  2,  3,  2,  4,  2,  1,  2,  3],
       [ 4,  2,  1,  1,  1,  1,  3,  1,  4,  9],
       [ 5,  8,  3,  4,  2,  1,  6,  2,  3,  8],
       [ 7,  6,  9, 10,  5,  3,  4,  7,  2,  5]])

In [ ]:
solution = 0
for i in board_large:
  print(str(solution), str(np.prod(i)))
  solution += np.prod(i)

0 8164800
8164800 61440
8226240 8640
8234880 7560
8242440 6048
8248488 1800
8250288 1728
8252016 864
8252880 276480
8529360 15876000


In [ ]:
solution

24405360